// Product copy only. Token symbols, wallet names, addresses and protocol names stay unchanged.
export const chinese: Record<string, string> = {
  'bscan — BSC KOL tracker': 'bscan — BSC KOL 追踪工具',
  'Language': '语言', 'Main navigation': '主导航', 'Trades': '交易', 'Tokens': '代币', 'Leaderboard': '排行榜',
  'Radar': '雷达', 'Watchlist': '自选', 'Launches': '新币', 'Activity views': '活动视图', 'Token views': '代币视图',
  'Watchlist tokens': '自选代币', 'Star tokens to add them here': '点击星标，将代币添加到这里', '24h price change': '24 小时价格变化',
  'On BNB Chain': 'BNB 链', 'BNB Chain': 'BNB 链', 'bscan on X': 'bscan 的 X 主页',
  'BNB/USD price unavailable': 'BNB/USD 价格暂不可用', 'Chainlink BNB/USD updated {time}': 'Chainlink BNB/USD 更新于 {time}',
  'Search': '搜索', 'Search bscan': '搜索 bscan', 'Close search': '关闭搜索', 'Toggle menu': '切换菜单',
  'Search KOL, wallet, token, or contract': '搜索 KOL、钱包、代币或合约',
  'Search tracked KOL wallets and tokens on BNB Smart Chain.': '搜索 BNB 智能链上已跟踪的 KOL 钱包和代币。',
  'No tracked results. Try a contract address or KOL name.': '暂无结果，请尝试输入合约地址或 KOL 名称。',
  'KOLs': 'KOL', 'THE LIVE TAPE': '实时动态', 'Realtime trades': '实时交易',
  'Recent BNB Chain swaps from tracked KOL wallets.': '已跟踪 KOL 钱包在 BNB 链上的最新交易。',
  'Latest trade {time}': '最新交易 {time}', 'Waiting for trades': '等待交易', 'Tracked KOLs': '已跟踪 KOL',
  'Trades · 24h': '24 小时交易', 'Tokens · 24h': '24 小时代币', 'Last trade': '最近交易',
  'Recent activity': '最新动态', 'Live feed unavailable': '实时数据暂不可用',
  'Watching for the next trade': '等待下一笔交易', 'The API is reconnecting. Try again shortly.': '正在重新连接，请稍后重试。',
  'Trades from tracked KOL wallets will appear here automatically.': '已跟踪 KOL 钱包的新交易会自动显示在这里。',
  'FAQs': '常见问题', 'What does bscan track?': 'bscan 跟踪哪些数据？',
  'bscan shows token trades from a curated list of KOL wallets on BNB Smart Chain.': 'bscan 展示 BNB 智能链上精选 KOL 钱包的代币交易。',
  'How often do new trades appear?': '交易多久更新一次？',
  'The feed updates automatically as newly indexed trades become available.': '新交易完成索引后，交易列表会自动更新。',
  'What can I find in the token tracker?': '代币追踪器提供哪些信息？',
  'Browse tokens traded by tracked KOLs, grouped by market cap. Open a token to see its recent KOL trades and the wallets trading it.': '按市值浏览已跟踪 KOL 交易过的代币。打开代币详情可查看最新 KOL 交易及相关钱包。',
  'What does a KOL profile show?': 'KOL 主页显示哪些信息？',
  'Each tracked wallet has a profile with its last 24 hours of trades, traded tokens, and realized profit from positions bought and sold in that window.': '每个已跟踪钱包的主页展示过去 24 小时的交易、交易过的代币，以及在该时段内买入并卖出仓位的已实现收益。',
  'How does the leaderboard work?': '排行榜如何计算？',
  'It ranks tracked positions by realized USD profit over the last 24 hours. Sales without enough priced purchases in that window are excluded. A dash means there are no fully priced completed positions yet.': '排行榜按过去 24 小时的已实现美元收益排序。若该时段内缺少足够的买入成本数据，相关卖出不会计入。横线表示暂时没有价格数据完整的已平仓仓位。',
  'Follow us on X': '在 X 上关注我们', 'Updates from bscan.': 'bscan 最新消息。',
  'Observed price': '成交参考价', 'Market cap': '市值', '24h volume': '24 小时成交额', 'MC —': '市值 —', 'MC {value}': '市值 {value}',
  'KOL CONVICTION': 'KOL 动向', 'Meme coin tracker': 'Meme 代币追踪', 'Live feed reconnecting': '正在重新连接',
  'Watching live trades': '跟踪实时交易', 'Low caps': '低市值', 'Under $100K': '低于 10 万美元',
  '$100K+': '10 万美元以上', '$100K to $1M': '10 万至 100 万美元', '$1M+': '100 万美元以上', '$1M and above': '100 万美元及以上',
  'THE PERFORMANCE BOARD': '收益表现', 'KOL Leaderboard': 'KOL 排行榜',
  'Realized profit from positions bought and sold in the last 24 hours.': '过去 24 小时内买入并卖出仓位的已实现收益。',
  'Calculated {time}': '计算于 {time}', 'Calculating rankings': '正在计算排名',
  'LAST 24 HOURS · RANKED BY REALIZED P&L': '过去 24 小时 · 按已实现盈亏排序',
  '{active} active · {tracked} tracked KOLs': '{active} 个活跃 · {tracked} 个已跟踪 KOL',
  'trade': '笔交易', 'trades': '笔交易', 'buy': '买入', 'buys': '笔买入', 'sell': '卖出', 'sells': '笔卖出', 'swap': '兑换', 'unknown': '未知',
  '{matched} matched sales in the last 24 hours; {excluded} sales excluded because purchase costs or prices are unavailable': '过去 24 小时内匹配了 {matched} 笔卖出；{excluded} 笔因缺少买入成本或价格而未计入',
  'Unpriced sales': '卖出价格缺失', 'Missing purchase costs': '买入成本缺失', '24H realized P&L': '24 小时已实现盈亏',
  'Leaderboard unavailable': '排行榜暂不可用', 'No KOL trades in the last 24 hours': '过去 24 小时暂无 KOL 交易',
  'The API is reconnecting.': '正在重新连接。', 'Recent wallet activity will appear here automatically.': '钱包最新动态会自动显示在这里。',
  'Back to leaderboard': '返回排行榜', 'Back to tokens': '返回代币', 'KOL not found': '未找到 KOL',
  'This wallet is not in the supplied KOL roster.': '此钱包不在已跟踪的 KOL 名单中。',
  '24H tracked realized P&L': '24 小时已跟踪的已实现盈亏', 'Sale prices unavailable': '卖出价格暂不可用',
  'Purchase costs unavailable in the last 24 hours': '过去 24 小时的买入成本暂不可用',
  '{matched} matched sales · {excluded} excluded': '{matched} 笔已匹配卖出 · {excluded} 笔未计入',
  'Trades · last 24 hours': '过去 24 小时交易', '{buys} buys · {sells} sells · {zone}': '{buys} 笔买入 · {sells} 笔卖出 · {zone}',
  '{count} indexed trades from this wallet': '此钱包已索引 {count} 笔交易', 'No trades in the last 24 hours': '过去 24 小时暂无交易',
  'New swaps from this wallet will appear here automatically.': '此钱包的新交易会自动显示在这里。',
  'Loading trades…': '正在加载交易…', 'Load more trades': '加载更多交易', 'Could not load more trades. Try again.': '无法加载更多交易，请重试。',
  'Traded tokens': '交易过的代币', 'Recent token activity': '最新代币动态', 'No tracked tokens yet': '暂无已跟踪代币',
  'Tokens appear after a tracked swap.': '跟踪到交易后，相关代币会显示在这里。',
  'Loading tokens…': '正在加载代币…', 'Load more tokens': '加载更多代币', 'Could not load more tokens. Try again.': '无法加载更多代币，请重试。',
  'Token not found': '未找到代币', 'No tracked KOL has traded this contract yet.': '暂无已跟踪 KOL 交易过此合约。',
  'KOLs · 24h': '24 小时 KOL 数', '24h KOL volume': '24 小时 KOL 成交额', 'KOL trades': 'KOL 交易',
  'Recent activity in this token': '此代币的最新动态', 'KOLs trading it': '交易此代币的 KOL',
  'No tracked trades yet': '暂无已跟踪交易', 'New KOL trades in this token will appear here automatically.': '此代币的新 KOL 交易会自动显示在这里。',
  'Unknown': '未知', 'Copy {label}': '复制{label}', '{label} copied': '已复制{label}', 'Copied': '已复制', 'Copy failed': '复制失败',
  'KOL wallet address': 'KOL 钱包地址', 'Token contract address': '代币合约地址', 'View token on GMGN': '在 GMGN 查看代币',
  'View KOL profile on GMGN': '在 GMGN 查看 KOL 主页', 'View KOL wallet on BscScan': '在 BscScan 查看 KOL 钱包',
  'View wallet on BscScan': '在 BscScan 查看钱包', 'View contract on BscScan': '在 BscScan 查看合约',
  'View token contract on BscScan': '在 BscScan 查看代币合约', 'View KOL on X': '在 X 查看 KOL', 'Visit token website': '访问代币网站',
  'Automatic English translation': '自动英文翻译', 'Automatic translation of {name}': '{name} 的自动翻译', 'Translate name': '翻译名称',
  'Recorded BNB trade amount': '已记录的 BNB 交易金额',
  'Approximate BNB amount based on the current BNB/USD price': '按当前 BNB/USD 价格估算的 BNB 金额',
  'View token activity on GMGN': '在 GMGN 查看代币动态', 'View {token} activity on GMGN, {time}': '在 GMGN 查看 {token} 动态，{time}',
  'Recent {token} trades': '{token} 的最新交易', 'token': '代币',
  'Follow': '关注', 'Unfollow': '取消关注', '{action} {name}': '{action} {name}',
  'KOLs buying': 'KOL 集中买入', 'Buying again': '再次买入', 'Buyer selling': '买家卖出',
  'Near graduation': '即将毕业', 'Graduated': '已毕业', 'Corrected': '已更正',
  '{count} KOLs · {minutes}m': '{count} 个 KOL · {minutes} 分钟', '{count} buys · {minutes}m': '{count} 笔买入 · {minutes} 分钟',
  'Published': '发布于', 'Chain correction': '链上更正', 'Launch state': '发行状态', 'Confirmed': '已确认',
  'Loading radar…': '正在加载雷达…', 'Radar unavailable': '雷达暂不可用', 'No watched signals yet': '自选暂无信号', 'No signals yet': '暂无信号',
  'Loading…': '正在加载…', 'Load more': '加载更多', 'Could not load more. Try again.': '无法加载更多，请重试。',
  'Alerts': '提醒', 'Filters': '筛选', 'Window': '时间窗口', 'Buying window': '买入时间窗口', 'KOL threshold': 'KOL 数量门槛',
  '{minutes}m': '{minutes} 分钟', 'Muted': '已静音', 'Alerts on': '提醒已开启', 'Connected': '已连接', 'Disconnect': '断开连接',
  'Clear watchlist': '清空自选',
  'Watchlists': '自选列表',
  'Information shown on bscan': 'bscan 展示的信息', 'Information from your visit': '访问时收集的信息',
  'Signal not found': '未找到信号', 'Invalid tokens': '代币列表无效',
  'We store followed wallet and token addresses, filter settings, and a hashed browser-session secret. Watchlists belong to the browser that created them.': '我们保存您关注的钱包和代币地址、筛选设置以及经过哈希处理的浏览器会话密钥。自选列表归创建它的浏览器所有。',
  'Clear watchlist deletes your saved watchlist and preferences. Browser sessions expire after up to a year without a save. Clearing browser cookies loses access to that watchlist; cross-device recovery is unavailable.': '清空自选会删除已保存的自选列表及偏好设置。浏览器会话在最长一年未保存后过期。清除浏览器 Cookie 后将无法访问原自选列表，目前不支持跨设备恢复。',
  'No followed KOLs': '尚未关注 KOL', 'No followed tokens': '尚未关注代币', 'Watched signals': '自选信号',
  'Watchlist unavailable': '自选暂不可用', 'Could not save watchlist': '无法保存自选', 'Could not clear watchlist': '无法清空自选',
  'Try again shortly': '请稍后重试', 'Request failed ({status})': '请求失败（{status}）',
  'Holding': '持有', 'Added': '加仓', 'Reduced': '减仓', 'Exited': '已清仓', 'Transferred': '已转账',
  'Balance': '余额', 'Checked': '检查时间', 'Last movement': '最近变动', 'Checked {time}': '检查于 {time}', 'Not checked': '尚未检查',
  'Bonding': '曲线交易中', 'Tracked KOL tokens': '已跟踪 KOL 交易过的代币', 'Launchpad': '发行平台', 'All launchpads': '全部平台',
  'Launch stage': '发行阶段', 'All stages': '全部阶段', 'Observed {time}': '观测于 {time}', 'Liquidity unavailable': '流动性暂不可用',
  'Liquidity': '流动性', 'Loading launches…': '正在加载新币…', 'Launches unavailable': '新币数据暂不可用', 'No tracked launches yet': '暂无已跟踪新币',
  'Launch': '发行', 'First KOL': '首笔 KOL 交易', 'Time unavailable': '时间暂不可用', 'Observed': '当前观测值',
  'Since first observation': '较首次观测', 'First observation': '首次观测', 'Migration': '迁移交易', 'Pool': '资金池', 'Pool ID': '资金池 ID',
  'BNB Smart Chain KOL analytics.': 'BNB 智能链 KOL 数据分析。', 'Legal': '法律信息', 'LEGAL': '法律信息',
  'Privacy Policy': '隐私政策', 'Terms of Use': '使用条款', 'Back to bscan': '返回 bscan', 'Last updated October 4, 2026': '最后更新：2026 年 10 月 4 日',
  'How we use information': '信息的使用方式', 'External services': '外部服务', 'Retention and your choices': '信息保留与您的选择',
  'Contact and changes': '联系方式与更新', 'What the service does': '服务内容', 'Data and limitations': '数据与局限',
  'No investment advice': '不构成投资建议', 'Using the site': '网站使用规则', 'External links and availability': '外部链接与可用性',
  'bscan is a public, read-only BNB Smart Chain analytics site. You can browse it without creating an account or connecting a wallet.': 'bscan 是公开、只读的 BNB 智能链数据分析网站。无需注册账户或连接钱包即可浏览。',
  'We display public wallet addresses, blockchain transactions, token data, and analytics derived from them. The tracked wallet roster also contains KOL names and X handles supplied to bscan, and may include publicly available profile images. A name or handle shown beside a wallet is not independent proof of who owns it.': '我们展示公开的钱包地址、区块链交易、代币数据及相关分析。已跟踪钱包名单还包含提供给 bscan 的 KOL 名称和 X 用户名，以及可能公开可见的头像。钱包旁显示的名称或用户名不能作为其所有者身份的独立证明。',
  'When you use the site, normal web requests send your IP address, browser information, requested pages, and any search terms you enter to our server. Basic request and error logs may contain this information. Browsing does not require an account. If you save a watchlist, we set an essential, secure HttpOnly cookie to recognize that browser. We do not use a third-party analytics script.': '使用网站时，正常网络请求会将您的 IP 地址、浏览器信息、访问页面及输入的搜索词发送至服务器。基本请求日志和错误日志可能包含这些信息。浏览无需账户。保存自选列表时，我们会设置必要的安全 HttpOnly Cookie 以识别该浏览器。我们不使用第三方分析脚本。',
  'We use public data to display the trade feed, token pages, KOL profiles, and leaderboard. We use request information to deliver the site, diagnose problems, and protect the service. Where applicable, this processing supports our legitimate interest in operating and securing a public analytics service.': '我们使用公开数据展示交易列表、代币页面、KOL 主页和排行榜。请求信息用于提供网站服务、排查问题及保护服务安全。在适用情况下，这些处理基于我们运营和保护公开分析服务的合法利益。',
  'Some token images load from external hosts, which may receive standard request information from your browser. Links to X, BscScan, and GMGN take you to services with their own privacy practices. Our hosting provider processes information needed to deliver bscan. We send public token names to MyMemory to provide cached English translations; these requests do not include your browser identifiers or watchlist.': '部分代币图片从外部服务器加载，这些服务器可能收到浏览器的标准请求信息。X、BscScan 和 GMGN 链接指向采用各自隐私规则的服务。托管服务商会处理提供 bscan 所需的信息。我们将公开代币名称发送至 MyMemory，以提供缓存的英文翻译；这些请求不包含您的浏览器标识或自选列表。',
  'We keep indexed public blockchain data and roster information while they are needed to run the service. Operational logs are kept only as long as needed for service and security purposes. You may ask us about access, correction, or removal of off-chain profile information, or object to its use. Public blockchain records cannot be changed by bscan. Depending on where you live, you may also have a right to complain to a privacy regulator.': '我们在运营服务所需期间保留已索引的公开区块链数据和名单信息。运营日志仅在服务与安全所需期间保留。您可以就链下个人资料信息请求访问、更正或删除，或反对其使用。bscan 无法更改公开区块链记录。根据您所在地区，您也可能有权向隐私监管机构投诉。',
  'For privacy questions or requests, email': '如有隐私问题或请求，请发送邮件至',
  '. We may update this policy as the service changes; the date above shows the latest version.': '。我们可能随服务变化更新本政策；上方日期为最新版本日期。',
  'These terms apply to your use of bscan, a public, read-only BNB Smart Chain analytics site.': '本条款适用于您使用 bscan 这一公开、只读的 BNB 智能链数据分析网站。',
  'bscan displays observed transactions from a curated list of wallets, token activity, KOL profiles, and a realized profit and loss leaderboard. The site does not connect to your wallet or execute trades.': 'bscan 展示精选钱包名单的已观测交易、代币动态、KOL 主页及已实现盈亏排行榜。本网站不会连接您的钱包或执行交易。',
  'Blockchain and third-party data may be delayed, incomplete, inaccurate, or unavailable. Wallet names and X handles are not independently verified. Prices are based on observed trades, and realized profit and loss can be partial when earlier buys or reliable USD values are unavailable. Do not treat these figures as a complete account history or a live market quote.': '区块链及第三方数据可能存在延迟、不完整、不准确或不可用的情况。钱包名称和 X 用户名未经独立验证。价格基于已观测交易；若缺少早期买入记录或可靠的美元估值，已实现盈亏可能不完整。请勿将这些数据视为完整账户记录或实时市场报价。',
  'Content on bscan is for general information. It is not financial, investment, tax, or legal advice, and it is not a recommendation to buy or sell any asset. Make your own assessment before acting on the information.': 'bscan 内容仅供一般参考，不构成金融、投资、税务或法律建议，也不构成买卖任何资产的推荐。请在采取行动前自行评估。',
  'You may use the site for lawful purposes. Do not try to disrupt the service, bypass its safeguards, or interfere with other visitors. We may change, suspend, or stop any part of bscan.': '您可以为合法目的使用本网站。请勿破坏服务、绕过安全措施或干扰其他访客。我们可能更改、暂停或停止 bscan 的任何部分。',
  'Links to X, BscScan, GMGN, and other sites are provided for convenience. We do not control those services. bscan is provided as available, without a guarantee that it will be uninterrupted or error-free. To the extent permitted by law, bscan is not responsible for losses caused by reliance on the site or by third-party services.': 'X、BscScan、GMGN 及其他网站链接仅为方便用户提供。我们不控制这些服务。bscan 按现有可用状态提供，不保证服务持续不中断或无错误。在法律允许的范围内，bscan 不对依赖本网站或使用第三方服务造成的损失负责。',
  'For questions about these terms, email': '如对本条款有疑问，请发送邮件至',
  '. We may revise these terms; the date above shows the latest version.': '。我们可能修订本条款；上方日期为最新版本日期。',
  'Language preference': '语言偏好',
  'Your language choice is saved in this browser’s local storage.': '您的语言选择保存在该浏览器的本地存储中。',
  'just now': '刚刚', '{seconds}s ago': '{seconds} 秒前', '{minutes}m ago': '{minutes} 分钟前', '{hours}h ago': '{hours} 小时前', '{days}d ago': '{days} 天前',
  'Invalid settings': '设置无效', 'Invalid category': '提醒类别无效', 'Invalid watchlist': '自选列表无效',
  'Invalid item': '自选项目无效', 'Invalid address': '地址无效', 'Too many followed items': '关注的项目过多',
  'Could not update settings. Try again.': '无法更新设置，请重试。',
  'Request origin rejected': '请求来源无效', 'Invalid cursor': '分页标识无效',
  'Watch up to 100 KOLs and 100 tokens': '最多可关注 100 个 KOL 和 100 个代币',
  'Only tracked KOLs and traded tokens can be followed': '仅可关注已跟踪的 KOL 和已交易的代币',
  'Internal Server Error': '服务暂不可用，请稍后重试',
  'Token watchlist': '代币自选', 'Your saved tokens, at a glance.': '一览您已保存的代币。',
  'Add tokens': '添加代币', '{count} tokens': '{count} 个代币', 'Search watched tokens': '搜索自选代币',
  '1h': '1小时', '24h': '24小时', 'Name': '名称', 'Tracked volume (24h)': '跟踪交易量（24小时）',
  'KOLs (24h)': 'KOL（24小时）', 'Chart (24h)': '走势（24小时）', 'No matching tokens': '没有匹配的代币',
  'View token watchlist': '查看代币自选',
  'Charts and volume use recorded KOL trades. Missing data is shown as a dash.': '走势和交易量基于已记录的 KOL 交易。缺失数据以横线显示。',
  'Token price chart': '代币价格图表',
  'Token price chart · 24h': '代币价格图表 · 24小时',
  'Token price chart · 1 week': '代币价格图表 · 1周',
  'Token price chart · 1 month': '代币价格图表 · 1个月',
  'Market candles': '市场K线',
  'Recorded trades': '已记录交易',
  'Latest available quote': '最新可用报价',
  'Loading market chart…': '正在加载市场图表…',
  'Market chart unavailable': '市场图表暂不可用',
  'Open live chart': '打开实时图表',
  'Candles': 'K线',
  'Loading candles…': '正在加载K线…',
  'Candle data unavailable': '暂时没有K线数据',
  'candles': '根K线',
  'Line': '折线',
  'Cached': '缓存数据',
  'Refresh paused': '刷新已暂停',
  'Reset': '重置',
  'Recorded trade prices in the last 24 hours': '过去24小时记录的交易价格',
  'Recorded trade prices in the last week': '过去一周记录的交易价格',
  'Recorded trade prices in the last 30 days': '过去30天记录的交易价格',
  'English translation': '英文翻译', 'Token time range': '代币时间范围', 'Contract address': '合约地址', 'Sort by chart price change': '按走势图价格变化排序',
  '1 week': '1周', '1 month': '1个月', 'Tracked volume': '跟踪交易量', 'Chart': '走势', 'Updating…': '更新中…', 'Token market details': '代币市场详情', 'Token market data unavailable': '代币市场数据暂不可用',
};
